AWSTemplateFormatVersion: "2010-09-09"
Description: "AlertResponder https://github.com/m-mizutani/AlertResponder"
Transform: AWS::Serverless-2016-10-31
Parameters:
  LambdaRoleArn:
    Type: String
    Default: ""
  StepFunctionRoleArn:
    Type: String
    Default: ""
  ReviewerLambdaArn:
    Type: String
  InspectionDelay:
    Type: Number
    Default: 300
  ReviewDelay:
    Type: Number
    Default: 600

Conditions:
  LambdaRoleRequired:
    Fn::Equals: [ { Ref: LambdaRoleArn }, "" ]
  StepFunctionRoleRequired:
    Fn::Equals: [ { Ref: StepFunctionRoleArn }, "" ]

Globals:
  Function:
    Runtime: go1.x
    CodeUri: build
    Timeout: 30
    MemorySize: 128

Resources:
  # --------------------------------------------------------
  # DynamoDBs
  AlertMap:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: alert_id
        AttributeType: S
      - AttributeName: timestamp
        AttributeType: S
      KeySchema:
      - AttributeName: alert_id
        KeyType: HASH
      - AttributeName: timestamp
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  ReportData:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: report_id
        AttributeType: S
      - AttributeName: data_id
        AttributeType: S
      KeySchema:
      - AttributeName: report_id
        KeyType: HASH
      - AttributeName: data_id
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  # --------------------------------------------------------
  # Kinesis Stream
  TaskStream:
    Properties:
      RetentionPeriodHours: 24
      ShardCount: 1
    Type: AWS::Kinesis::Stream

  # --------------------------------------------------------
  # StateMachines
  DelayDispatcher:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName:
        Fn::Sub: ["${StackName}-delay-dispatcher", {"StackName": {"Ref": "AWS::StackName"} }]
      RoleArn:
        Fn::If: [ StepFunctionRoleRequired, {"Fn::GetAtt": StepFunctionRole.Arn}, {Ref: StepFunctionRoleArn} ]
      DefinitionString:
        !Sub
          - |-
            {"StartAt":"Waiting","States":{"Waiting":{"Type":"Wait","Next":"Exec","Seconds":${delay}},"Exec":{"Type":"Task","Resource":"${lambdaArn}","End":true}}}
          - {lambdaArn: !GetAtt [ Dispatcher, Arn ], delay: {Ref: InspectionDelay }}

  ReviewInvoker:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName:
        Fn::Sub: ["${StackName}-review-invoker", {"StackName": {"Ref": "AWS::StackName"} }]
      RoleArn:
        Fn::If: [ StepFunctionRoleRequired, {"Fn::GetAtt": StepFunctionRole.Arn}, {Ref: StepFunctionRoleArn} ]
      DefinitionString:
        !Sub
          - |-
            {"StartAt":"Wating","States":{"Wating":{"Type":"Wait","Next":"Compiler","Seconds":${delay}},"Compiler":{"Type":"Task","Resource":"${compilerArn}","Catch":[{"ErrorEquals":["States.ALL"],"ResultPath":"$.error","Next":"ErrorHandler"}],"Next":"CheckPolicy"},"CheckPolicy":{"Type":"Task","Resource":"${policyLambdaArn}","Catch":[{"ErrorEquals":["States.ALL"],"ResultPath":"$.error","Next":"ErrorHandler"}],"ResultPath":"$.result","Next":"Publish"},"ErrorHandler":{"Type":"Task","Resource":"${errorHandlerArn}","End":true},"Publish":{"Type":"Task","Resource":"${publisherArn}","End":true}}}
          - policyLambdaArn:
              Ref: ReviewerLambdaArn
            compilerArn:
              Fn::GetAtt: Compiler.Arn
            publisherArn:
              Fn::GetAtt: Publisher.Arn
            errorHandlerArn:
              Fn::GetAtt: ErrorHandler.Arn
            delay:
              Ref: ReviewDelay

  # --------------------------------------------------------
  # Lambda functions
  Receptor:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build
      Handler: receptor
      Role:
        Fn::If: [ LambdaRoleRequired, {"Fn::GetAtt": LambdaRole.Arn}, {Ref: LambdaRoleArn} ]
      Environment:
        Variables:
          ALERT_MAP:
            Fn::Sub: ${AlertMap}
          DISPATCH_MACHINE:
            Ref: DelayDispatcher
          REVIEW_MACHINE:
            Ref: ReviewInvoker
          REPORT_LINE:
            Ref: ReportLine
      Events:
        NotifyTopic:
          Type: SNS
          Properties:
            Topic:
              Ref: AlertNotification


  Dispatcher:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build
      Handler: dispatcher
      Environment:
        Variables:
          STREAM_NAME:
            Fn::Sub: ${TaskStream}
      Role:
        Fn::If: [ LambdaRoleRequired, {"Fn::GetAtt": LambdaRole.Arn}, {Ref: LambdaRoleArn} ]

  Compiler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build
      Handler: compiler
      Environment:
        Variables:
          REPORT_DATA:
            Ref: ReportData
      Role:
        Fn::If: [ LambdaRoleRequired, {"Fn::GetAtt": LambdaRole.Arn}, {Ref: LambdaRoleArn} ]

  Publisher:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build
      Handler: publisher
      Environment:
        Variables:
          REPORT_LINE:
            Ref: ReportLine
      Role:
        Fn::If: [ LambdaRoleRequired, {"Fn::GetAtt": LambdaRole.Arn}, {Ref: LambdaRoleArn} ]

  ErrorHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build
      Handler: compiler
      Role:
        Fn::If: [ LambdaRoleRequired, {"Fn::GetAtt": LambdaRole.Arn}, {Ref: LambdaRoleArn} ]

  # --------------------------------------------------------
  # SNS topics
  AlertNotification:
    Type: AWS::SNS::Topic

  TaskNotification:
    Type: AWS::SNS::Topic

  ReportLine:
    Type: AWS::SNS::Topic

  # --------------------------------------------------------
  # IAM Roles
  LambdaRole:
    Type: AWS::IAM::Role
    Condition: LambdaRoleRequired
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: ["lambda.amazonaws.com"]
            Action: ["sts:AssumeRole"]
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      Policies:
        - PolicyName: "AlertResponderLambdaReviewer"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - dynamodb:PutItem
                  - dynamodb:DeleteItem
                  - dynamodb:GetItem
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:UpdateItem
                Resource:
                  - Fn::GetAtt: AlertMap.Arn
                  - Fn::Sub: [ "${TableArn}/index/*", { TableArn: { "Fn::GetAtt": AlertMap.Arn } } ]
                  - Fn::GetAtt: ReportData.Arn
                  - Fn::Sub: [ "${TableArn}/index/*", { TableArn: { "Fn::GetAtt": ReportData.Arn } } ]
              - Effect: "Allow"
                Action:
                  - sns:Publish
                Resource:
                  - Ref: ReportLine
              - Effect: "Allow"
                Action:
                  - kinesis:PutRecord
                  - kinesis:PutRecords
                Resource:
                  - Fn::GetAtt: TaskStream.Arn
              - Effect: "Allow"
                Action:
                  - states:StartExecution
                Resource:
                  - Fn::Sub:
                    - "arn:aws:states:${Region}:${Account}:stateMachine:${StackName}-delay-dispatcher"
                    - StackName: {"Ref": "AWS::StackName"}
                      Region: {"Ref": "AWS::Region"}
                      Account: {"Ref": "AWS::AccountId" }
                  - Fn::Sub:
                    - "arn:aws:states:${Region}:${Account}:stateMachine:${StackName}-review-invoker"
                    - StackName: {"Ref": "AWS::StackName"}
                      Region: {"Ref": "AWS::Region"}
                      Account: {"Ref": "AWS::AccountId" }

  StepFunctionRole:
    Type: AWS::IAM::Role
    Condition: StepFunctionRoleRequired
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: {"Fn::Sub": ["states.${Region}.amazonaws.com", {"Region": {"Ref": "AWS::Region" }}]}
            Action: ["sts:AssumeRole"]
      Path: "/"
      Policies:
        - PolicyName: "AlertResponderLambdaInvokeReviewer"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - Ref: ReviewerLambdaArn
                  - Fn::GetAtt: Dispatcher.Arn
                  - Fn::GetAtt: ErrorHandler.Arn
                  - Fn::GetAtt: Compiler.Arn
                  - Fn::GetAtt: Publisher.Arn

